### PR TITLE
Custom indexing for revoke, revoke/purge without actual token, and bug fix for tests. 

### PR DESCRIPTION
**Pull request by yaacovCR**
Add mongodb store for convenience, not necessarily for productive environments.
Also changes integration tests to run in parallel rather than series so blacklist.configure calls do not conflict.

### CODE REVIEW

**Comment by nilgradisnik** [comment]
@yaacovCR Sorry for such late response and thanks for submitting this.
Although I don't think doing MongoDB lookup for every request is a good idea, I will take a look at this asap.

**Comment by yaacovCR** [comment]
The MongoDB store was just for fun. The other changes, though, I still like/want/need. My basic issue is that my token refresh scheme maintains the same jwt id, which is assigned one per session, so I would like to revoke all tokens with that jwt id. I would also like an admin user, given that jwt id, to be able to revoke that session. This pull request should enable those changes?

**Comment by nilgradisnik** [comment]
I am reluctant to merge this one because it is trying to solve more than one thing at once. If you decouple the MongoDB feature into a separate branch we can pick it up from there.

I have not problem merging the other changes regarding `tokenId` and `indexBy` options, optional callbacks, async tests changes and the readme additions as well.

**Comment by yaacovCR** [comment]
Sounds reasonable. I'll try to get to it.

**Comment by nilgradisnik** [comment]
@yaacovCR This looks good to me. Once you squash all the commits I'll merge it.

**Comment by yaacovCR** [comment]
I think redis store assumes key is number, which probably should fail this change if I had added the right tests...

**Pull request merged**
